# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20161123_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='q_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='r_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='r_text',
            new_name='text',
        ),
    ]
